name       : xcb-proto
version    : '1.14'
release    : 10
source     :
    - https://www.x.org/releases/individual/xcb/xcb-proto-1.14.tar.gz : 1c3fa23d091fb5e4f1e9bf145a902161cec00d260fabf880a7a248b02ab27031
license    : MIT
component  : xorg.proto
summary    : XML-XCB Protocol
description: |
    The xcb-proto package provides the XML-XCB protocol descriptions that libxcb uses to generate the majority of its code and API.
patterns   : /
environment:
    export PYTHON="python3"
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
