name       : xcb-proto
version    : '1.15'
release    : 14
source     :
    - https://xorg.freedesktop.org/archive/individual/proto/xcb-proto-1.15.tar.gz : 0e434af76af722ef9b2dc21066da1cd11e5dd85fc1996d66228d090f9ae9b217
license    : MIT
component  : xorg.proto
summary    : XML-XCB Protocol
description: |
    The xcb-proto package provides the XML-XCB protocol descriptions that libxcb uses to generate the majority of its code and API.
patterns   : /
environment: |
    export PYTHON="python3"
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
