name       : xcb-proto
version    : 1.14.1
release    : 11
source     :
    - https://xorg.freedesktop.org/archive/individual/proto/xcb-proto-1.14.1.tar.gz : 85cd21e9d9fbc341d0dbf11eace98d55d7db89fda724b0e598855fcddf0944fd
license    : MIT
component  : xorg.proto
summary    : XML-XCB Protocol
description: |
    The xcb-proto package provides the XML-XCB protocol descriptions that libxcb uses to generate the majority of its code and API.
patterns   : /
environment: |
    export PYTHON="python3"
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
