name        : xcb-proto
version     : 1.11
release     : 6
source      :
    - http://xorg.freedesktop.org/releases/individual/xcb/xcb-proto-1.11.tar.bz2 : b4aceee6502a0ce45fc39b33c541a2df4715d00b72e660ebe8c5bb444771e32e
license     :
    - MIT
summary     : XML-XCB Protocol
component   : xorg.proto
patterns    : /
description : |
    The xcb-proto package provides the XML-XCB protocol descriptions that libxcb uses to generate the majority of its code and API.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
