name       : xcb-proto
version    : '1.13'
release    : 8
source     :
    - https://www.x.org/releases/individual/xcb/xcb-proto-1.13.tar.gz : 0698e8f596e4c0dbad71d3dc754d95eb0edbb42df5464e0f782621216fa33ba7
license    :
    - MIT
summary    : XML-XCB Protocol
component  : xorg.proto
patterns   : /
description: |
    The xcb-proto package provides the XML-XCB protocol descriptions that libxcb uses to generate the majority of its code and API.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
