name       : xcb-proto
version    : '1.14'
release    : 9
source     :
    - https://www.x.org/releases/individual/xcb/xcb-proto-1.14.tar.gz : 1c3fa23d091fb5e4f1e9bf145a902161cec00d260fabf880a7a248b02ab27031
license    :
    - MIT
summary    : XML-XCB Protocol
component  : xorg.proto
patterns   : /
description: |
    The xcb-proto package provides the XML-XCB protocol descriptions that libxcb uses to generate the majority of its code and API.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
