name       : xcb-proto
version    : 1.15.2
release    : 16
source     :
    - https://xorg.freedesktop.org/archive/individual/proto/xcb-proto-1.15.2.tar.xz : 7072beb1f680a2fe3f9e535b797c146d22528990c72f63ddb49d2f350a3653ed
license    : MIT
component  : xorg.proto
summary    : XML-XCB Protocol
description: |
    The xcb-proto package provides the XML-XCB protocol descriptions that libxcb uses to generate the majority of its code and API.
patterns   : /
environment: |
    export PYTHON="python3"
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
